### ISSUE TITLE
lz4 arşiv adresi yanlış

### ISSUE THREAD

**Issue by ayhanyalcinsoy** [milisarge/malfs-milis#1]
Doğrusu şöyle olmalı
https://github.com/Cyan4973/lz4/archive/lz4-r131.tar.gz

**Comment by milisarge** [comment]
talimatname/temel/lz4 kaynak adresi : https://github.com/Cyan4973/lz4/archive/r131.tar.gz  kontrol ettim link çalışıyor.sizin yazdığınız adrese not found hatası veriyor.
