### ISSUE TITLE
KDE Ortamı Giriş Bilgileri

### ISSUE THREAD

**Issue by BTaskaya** [milisarge/malfs-milis#159]
Milis XFCE4'den KDE5'e geçiş yaptım fakat bize verilen giriş bilgileri çalışmıyor.

```
Username: root #Çalışmıyor
Password: milis #Denenmedi
```
Çalışma Ortamı: VMware

**Comment by milisarge** [comment]
sağ altta login diffrent user seçeneği var.onunla giriş yapacaksınız.yeni gelen ekrana username : milis 
password : milis  girerek giriş yapabilirsiniz. Kde isomuz eski üsrümlere sahip bu arada son güncel xfce4 isoyu kurmanızı tavsiye ederiz.

**Comment by BTaskaya** [comment]
Teşekkürler, Normalde XFCE4 Kullanıyordum fakat KDE'ye ayrı bir aşığım :1st_place_medal:
