### ISSUE TITLE
MPS ve Milis Linux  için birkaç öneri

### ISSUE THREAD

**Issue by geekdinazor** [milisarge/malfs-milis#2]
Milis Linux ve onun paket yöneticisi MPS  için mevcut Linux dağıtımlarından gelen bazı alışkanlıklarımı ve rahatsızlık duyduğum noktaları içeren bazı küçük önerilerim şunlar:
- [ ]  Debiandaki gibi stabil çalışan eli yüzü düzgün bir grafiksel kurulum aracı. (Mümkünse Ubuntudaki ubiquity gibi her şeyi yapayım derken kendisi patlamayan bir tane :smile: )  
- [x] Yine kurulum esnasında herşeyin _out of box_  gelmesi yerine kurmak istediğimiz yazılımları seçebilmemiz. (Zira şahsen sistemle birlikte gelen ama hiç bir zaman kullanmayacağım/ muadillerini kullandığım yazılımları kaldırırken sinir oluyorum :-1: ) 
- [ ] Milis Linux'un öncelikli amacı stabiliteyi sağlamak olduğundan deponun Debian'a benzer bir şekilde **stabil** ve **test** olarak ikiye ayrılmasını öneriyorum. Kararsız çalışabileceğini düşündüğünüz fakat sık kullanılan paketlerin de depoda olması paket sayısının artması bakımından olumlu yönde etkiler.
- [ ]  Diğer paketler için kullanıcıların kendi talimatlarını yazabildiği mümkünse AUR tarzı bir platform yaratabilirseniz sürekli paket üretmek ile uğraşmayıp buglar ve yeni özellikler üzerine yoğunlaşabilirsiniz.
- [X]  Depolardaki mevcut paket adları yeniden adlandırmaya gerek duymayacak şekilde adlandırılır ve eski versiyonu da kullanılabilecek kritik paketler sürüm bilgisini de içinde bulundurursa -- **Örneğin libqt-qtbase yerine libqt5-qtbase gibi ya da sadece akonadi yerine (ki akonadi güncellenebilir, bu durumda kde5 çıktığında kde4 kullanmak isteyen birinin de mağdur olmaması açısından) kde4-akonadi, kde5-akonadi gibi** --  Arch Linux ve türevlerinde olduğu gibi yükseltme sırasında bi paketin 2 farklı adı yüzünden oluşan çakışmalar bertaraf edilmiş olur.  
- [X] Yine paket adlandırma politikaları içerisinde üstteki kural da göz önünde bulundurularak Debian ya da Arch gibi büyük dağıtımlar ile paralel olarak gidilmesi doğal olarak bu dağıtımlardan en az birisini kullanmış birisinin paket adlarına aşinalığını sağlar. 

Şimdilik aklıma gelen bunlar, daha sonra aklıma gelirse daha sonra yazarım. :smile_cat: 
_milis_cat_

**Comment by milisarge** [comment]
1-Grafiksel Kurulum Aracı
Milis Linux için genel manada sisteme ait herşeyi yönetebileceğiniz bir yapı var "komutan" adlı web tabanlı sistem betik ve wiki yönetim sistemi ayrıca Komutan'da yazdıgınız betiklerin basit şekilde değişken girme arayüzü oluşturma yeteneği de var.Sisteme ait arayüzle alakalı herşeyin Komutan üzerinden yürütülmesini istiyoruz.Kurulu,paket yönetimi,gerekli ayarlamalar vs...
Fakat bu demek değildir ki herşey Komutan üzerinden yapılacak her programın konsol tabanlı karşılığı var olacaktır.Şu an için esnek bir kurulumu destekleyen hem de kullanıcıların kurulum olayını daha iyi anlayabilmeleri için adım adım konsol komutlarıyla kurulumu öneriyoruz.Bu yöntemin avantajlı yanı da kullanıcının çalışan isoda yaptığı değişiklerle kurulumu yapabilmesidir.Böyllikle kullanıcı öntanımlı programlarla yüklü gelen milis linux u değil de kendi özelleştirdiği milisi kurma avantajına sahip olur. Ama ilerleyen zamanlarda geliştircillerin artması ve kullanıcılarımızdan gelen yoğun istekle native bir kurulum arayüzü tasarlanıp,yapılabilir.

**Comment by milisarge** [comment]
2-Depolar 
Evet depolar stabil ve test  depo olarak ayrılabilir bu iyi fikir fakat test depodaki paketler ana kural olarak stabil depoyla çakışmaması lazım kısaca test depo stabil depoya geçmeyi bekleyen paketlerden oluşmalı.

**Comment by geekdinazor** [comment]
@milisarge yani anladığım kadarıyla kurulum işlemi komutan ile yapılacak ?? Web tabanlı kurulum kulağa ilginç geliyor, bunu bi ara kanalda konuşabiliriz :dizzy_face: :sunglasses:

**Comment by milisarge** [comment]
3-Aur tarzı platform
Evet kullanıcıların kendi talimatlarını yazıp paket üretebilmesi için gerekli ortamımız hazır.
[derleme ortamı](https://milis.gungre.ch/iso/milis-bootstrap-enson.sfs) indirilip github dan forkladıkları talimatnameye ek paket talimatları eklenebilir,paketler test edildikten sonra da ana depoyla birleştirilecektir.

**Comment by milisarge** [comment]
4-Paket Adlandırılmaları
Paket adlandırmada belli bir kurala uymaya çalışıyoruz,örneğin python-xxx pyton2 sürümü için fakat python3 sonra çıktığı için xxx kütüphanesi için python3-xxx kullanıyoruz.

**Comment by milisarge** [comment]
otter browser depoya konsun.

**Comment by yusufgogus50** [comment]
steam olmakı ama öncelik sizin gibi tecrübeli adamlarda.

**Comment by yusufgogus5** [comment]
Çöksün siktir olup gitsin nefret ediyorum sıçıyım türk yapımı oluşuna durduk yere slack takımından deaktif ettiler tövbe tövbe o küfürler için.
