### ISSUE TITLE
MPS Paket Sistemi

### ISSUE THREAD

**Issue by samettirpan** [milisarge/malfs-milis#207]
Geliştirici arkadaşlara önce kolay gelsin güzel bir proje ancak eğer yurtdışına da açılmak istiyorsanız terminaldeki mps komutlarının türkçe olmaması kanaatindeyim. İlla da ingilizce olacak diye de bir şey yok, örneğin pardusta paket yüklerken "sudo pisi it program_adi" şeklinde bir komut veriyorduk.

**Comment by geekdinazor** [comment]
MPS'de parametre eklemek çok kolay kur/sil/guncelle/yukselt gibi komutlara ingilizce aliaslar verilebilir. Bu durumda komutlar mps install/remove/update/upgrade şeklinde kullanılabilir fakat tabi mps'nin de İngilizceye çevrilmesi, İngilizce komutlarda İngilizce çıktı verilmesi gerek. Anadili Türkçe olmayan arkadaşlardan istek geldikçe bu seçeneği değerlendirebiliriz. Doğal dil parametreleri, "it" gibi kısaltmalardan daha akılda kalıcı ve insancıl olduğundan son kullanıcı parametrelerini bu şekilde oluşturmayı tercih etmekteyiz. Tabi isteyen o fonksiyonun karşılığı olan, kısa API parametrelerini de kullanabilir. Seçim sizin :)
