### ISSUE TITLE
Projeler

### ISSUE THREAD

**Issue by giresun28** [milisarge/malfs-milis#48]
1) Komutan, Yazılım Merkezi, Kurulum adında 3 farklı .desktop dosyası yapılıp masaüstüne atılmalı.

2) Yazılım Merkezi .dektop dosyasına root yetkisi verilip yapılmalı ve ayrıca oluyorsa komutandan ayrılıp açılışta kullanıcı adı şifre sormaması gerekli.

3) Yazılım Merkezi'nde programlar kategorilere göre ayrılmalı.

4) Yazılım Merkezi'nde tüm programlar kategoriler halinde görünmeli.

**Comment by hwpplayer1** [comment]
root yetkisi sorun olmaz mı ?

**Comment by yusufgogus50** [comment]
sadece kategorilere ayrılsın çok karışık.
