### ISSUE TITLE
Çalışan-Kurulan İso İmajları Hakkında

### ISSUE THREAD

**Issue by milisarge** [milisarge/malfs-milis#6]
iso açılış yöneticisi gelsin!
**lxdm kurularak açılış yöneticisi sağlandı.**

**Comment by milisarge** [comment]
İso imajları aynı zamanda usb e kalıcı olarak kurulabilmeli.Normal sabit disk bölümüne kurar gibi.

**Comment by milisarge** [comment]
sanala kurulumun usb belleğe  sanal disk yerine.

**Comment by hwpplayer1** [comment]
Gnome Boxes sanal makinesine sanal.img dosyasını içeri alabildim. sanal.img dosyası açılıyor.

**Comment by milisarge** [comment]
1-bashrc_normal  eklenecek
2-mime tipler güncellenecek.(chroot içinde)

**Comment by milisarge** [comment]
rfkill wifi bloklamanması için gerekli
whiskermenu panelde ontanımlı gelsın
