### ISSUE TITLE
MPS İstek, Öneri ve Düzeltmeler

### ISSUE THREAD

**Issue by geekdinazor** [milisarge/malfs-milis#60]
- [X] ln failed hatasının kullanıcıya gösterilmemesi
- [X] İndirme sırasında süreç çubuğu (progressbar) gösterilmesi
- [X] Çeşitli parametre ismi düzeltmeleri (altta)
- [x] Çıktıların daha açıklayıcı ifadelerle düzeltilmesi 
- [X] Mümkünse sunucu değiştirmenin komut satırıyla yapılması

**Comment by yakar** [comment]
1. **mps** yerine **paket** veya **uygulama** adı kullanılabilir.
2. Çok kullanılan parametreler küçük harf ile kullanılabilir: -G ve -GG yerine -g ve -gg olarak tercih edilmeli.
3. Uzun parametreler standartlara uyulması açısından çift tire ile "--" kullanılmalı.
4. --sun yerine --sunucu kullanılabilir, akılda kalıcı olur.
5 Sunucu ekleme ve silme işlemleri için komutlar olmalı: --sunucu-ekle <sunucu> ve --sunucu-sil <sunucu> gibi
6. Paket silme işlemi için -s veya --sil şeklinde seçenek sunulmalı, standartlarda uzun açıklamalı parametreler veya tek harf şeklinde iki seçenek sunulmalıdır.
7. Tek paket güncelleme işlemi için de 6. maddede olduğu gibi olabilir fakat -g genel paket.vt güncellemesi için kullanılabileceğinden eğer paket adı belirtilirse tek paketi güncellemeli değilse paket.vt güncellemeli gibi (veya benzeri bir mantıkla) düzenlenebilir.
8. Paket kurma işleminde paket bağımlılıkları **yeni kurulacaklar**, **kurulu olanlar** ve toplam indirilecek dosya boyutu şeklinde tek mesaj ile verilirse daha az kafa karıştırıcı olduğu gibi daha bilgilendirici olabilir.

**Comment by geekdinazor** [comment]
Parametreler son kullanıcı parametreleri ve API parametreleri olarak ikiye ayrıldı. API parametrelerinin aynı kalmasına son kullanıcı parametrelerinin ise tiresiz cümle şeklinde olmasına karar verildi.
