### ISSUE TITLE
Takip edilen P2P projeleri

### ISSUE THREAD

**Issue by hwpplayer1** [milisarge/malfs-milis#61]
Takip edilen P2P projeleri bu listede yer alabilir. 

https://maidsafe.net/roadmap.html#network
https://maidsafe.net/
https://morph.is/v0.8/

**Comment by hwpplayer1** [comment]
https://github.com/warner/magic-wormhole
https://tahoe-lafs.org/trac/tahoe-lafs

**Comment by yusufgogus50** [comment]
Selam
