### ISSUE TITLE
Milis 1.0 Atilla Sürümü Yol Haritası Notları

### ISSUE THREAD

**Issue by milisarge** [milisarge/malfs-milis#7]
- [X] Öntanımlı bir açılış yöneticisinin(lxdm veya slim) gelmesi.

- [X] Mps paket yöneticisinin 1.0 sürümüyle yer alması yani paket kurulum,kaldırma,güncelleme,derleme-paketleme işlemlerini ayrıca depo,talimatname güncelleme işlemlerini sorunsuz yapar hale gelmesi.

- [ ] Komutan adlı web tabanlı sistem ayarlama ve paket yönetimini sağlayan yazılımın sistem üzerinde öntanımlı kurulu gelmesi ve kullanıcının arayüz düzeyinde işlemlerini komutan üzerinden yapabilmesi.  

- [X] Ofis uygulamaları için libreoffice web browser olarak firefox veya türevlerinden birinin derlenmiş paketiyle kurulu gelmesi ve sorunsuz çalışması.

**Comment by hwpplayer1** [comment]
Bir sonraki kod adı El-Cezeri olsun derim.

**Comment by geekdinazor** [comment]
Benim bir sonraki sürüm için kod adı önerim ise Ebu El Künefe 😊
22 Haz 2016 20:35 tarihinde "Mert Gör" <notifications@github.com> yazdı:
