### ISSUE TITLE
Bug : useradd ile kullanıcı hesabı açıldığında mps sistemi tanınmıyor

### ISSUE THREAD

**Issue by hwpplayer1** [milisarge/malfs-milis#8]
useradd ile kullanıcı hesabı açtım sonrasında startx komutu çalışmadı ve klasik UNIX X arayüzüne yönlendirdi. Bilgisayarı yeniden başlattım su ile root olup startx dedim ve GUI açıldı ancak sonra mps komutları çalışmamaya başladı. 

Teşekkürler.

**Comment by hwpplayer1** [comment]
normal kullanıcı ile root moduna geçildiğinde sistem komut satırında yolu göremediği için ilgili programı çalıştıramıyor

**Comment by milisarge** [comment]
2 kere mps -GG yaptığımızda gerekli tamirat yapılmaktadır.
